import { Inter } from "next/font/google";
import "./globals.css";
import FireFliesBackground from "@/Components/FireFliesBackground";
import Sound from "@/Components/Sound";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Naym Official",
  description: "Generated by naym hossen with next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <FireFliesBackground />
        <Sound />
      </body>
    </html>
  );
}
